# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hM34eUM9OAiZ79sdc1TkQCJK-lDDtJdf
"""

valor1 = int(input("ingrese un valor"))
valor2 = int(input("ingrese otro valor"))
valor3 = int(input("ingrese otro valor"))

calculo1 = valor1 + valor2
calculo2 = valor1/valor2
print("El resultado del calculo1 es " , calculo1 , "y el tipo es" , type(calculo1))
print ("El resultado del calculo2 es " , calculo2 , "y el tipo es",  type(calculo2))